In [64]:
from scipy import stats
from scipy.spatial.distance import euclidean
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')
plt.rcParams.update({'font.size': 16})
plt.rcParams['axes.facecolor'] = 'white'
import matplotlib as mpl
mpl.rcParams['grid.color'] = 'lightgrey'
#needed for all graphs
colors = ['black', 'yellowgreen', 'thistle', 'slategrey', 'm']
alphas = [1, .5, 1, 1, 1]
s = 5

from scipy.sparse import csr_matrix
from src.ItemItemRecommender import ItemItemRecommender
from sklearn.model_selection import train_test_split
from src.item_item_prototype import get_ratings_data, load_movies
import warnings
warnings.filterwarnings('ignore')


# little test matrix
def ratings_matrix():
    return np.array([[4, 4, 0, 2, 2],
                     [4, 0, 0, 3, 3],
                     [4, 0, 0, 1, 1],
                     [1, 1, 1, 2, 0],
                     [2, 2, 2, 0, 0],
                     [1, 1, 1, 0, 0],
                     [5, 5, 5, 0, 0]]).astype(float)

In [65]:
def sim_euclidean(u, v):
    return 1 / (1 + euclidean(u, v))

def sim_cosine(u, v):
    costheta = np.dot(u, v)/(np.linalg.norm(u) * np.linalg.norm(v))
    return 0.5 + 0.5 * costheta

In [66]:
# plan to impute ratings.
# input: given any two items U(i,j), and distance metric d:
# find the distance between the vectors of shared ratings
# output: matrix of distances between items

# for any two users, + distance metric
# find the distance between the vectors of shared ratings
# output: user distance matrix

# for each missing value:
# PEDRO:
# for all peter rated food
# sum(col dist: chk to item) * peter rating of j

# RILEY:
# normalize user distance matrix
# missing values = for each row
#sum across columns dist-to-peter * normed average 


In [67]:
# Pedro
utility = ratings_matrix()

n = utility.shape[0]
m = utility.shape[1]


# A matrix of distances between movies
def item_dist_mat(df):
    m = df.shape[1]
    M = df.T
    D_cos = np.zeros((m,m))
    D_euc = np.zeros((m,m))
    for i in range(m):
        for j in range(m):
            if i != j:
                z = (M[i]==0) + (M[j]==0)
                a,b = M[i][~z], M[j][~z]
                if len(a) > 0:
                    d_cos = (a.dot(b))/(np.sqrt(a.dot(a))*np.sqrt(b.dot(b)))
                    d_euc = np.sqrt(sum((a-b)**2))
                    D_cos[i,j] = d_cos
                    D_euc[i,j] = d_euc
    return D_cos, D_euc

item_weights = item_dist_mat(utility)[0]

# def user_mean_mat(df)
#     n = df.shape[0]
#     riley = df.mean(axis = 1)
#     sd = df.std(axis = 1)

# A matrix of distances between users
def user_dist_mat(df):
    m = df.shape[0]
    M = df
    D_cos = np.zeros((m,m))
    D_euc = np.zeros((m,m))
    for i in range(m):
        for j in range(m):
            if i != j:
                z = (M[i]==0) + (M[j]==0)
                a,b = M[i][~z], M[j][~z]
                if len(a) > 0:
                    d_cos = (a.dot(b))/(np.sqrt(a.dot(a))*np.sqrt(b.dot(b)))
                    d_euc = np.sqrt(sum((a-b)**2))
                    D_cos[i,j] = d_cos
                    D_euc[i,j] = d_euc
    return D_cos, D_euc

user_weights = user_dist_mat(utility)[0]


In [70]:
item_weights.shape # 5x5 #movies x #movies

(5, 5)

In [71]:
user_weights.shape # 7x7 #users x #users

(7, 7)

In [ ]:
def imputed_rating(utility_mat):
    n = utility_mat.shape[0]
    m = utility_mat.shape[1]
    for i in range(n):
        for j in range(m):
            

In [74]:
utility.mean(axis=1)*utility.std(axis=1)

array([3.59199109, 3.34664011, 1.76363261, 0.63245553, 1.17575508,
       0.29393877, 7.34846923])

In [75]:
utility

array([[4., 4., 0., 2., 2.],
       [4., 0., 0., 3., 3.],
       [4., 0., 0., 1., 1.],
       [1., 1., 1., 2., 0.],
       [2., 2., 2., 0., 0.],
       [1., 1., 1., 0., 0.],
       [5., 5., 5., 0., 0.]])

In [76]:
utility.mean(axis=1)

array([2.4, 2. , 1.2, 1. , 1.2, 0.6, 3. ])

In [77]:
utility.std(axis=1)

array([1.49666295, 1.67332005, 1.46969385, 0.63245553, 0.9797959 ,
       0.48989795, 2.44948974])

In [80]:
a = np.ones(5)
b = np.ones(5)*5
(a.dot(b))/(np.sqrt(a.dot(a))*np.sqrt(b.dot(b)))

0.9999999999999999

In [69]:
M[1]
z
M[1][~z]
M[0][~z]

array([4., 1., 2., 1., 5.])

In [12]:




utility.T

array([[4., 4., 4., 1., 2., 1., 5.],
       [4., 0., 0., 1., 2., 1., 5.],
       [0., 0., 0., 1., 2., 1., 5.],
       [2., 3., 1., 2., 0., 0., 0.],
       [2., 3., 1., 0., 0., 0., 0.]])

In [ ]:
# Riley


In [9]:
utility

array([[4., 4., 0., 2., 2.],
       [4., 0., 0., 3., 3.],
       [4., 0., 0., 1., 1.],
       [1., 1., 1., 2., 0.],
       [2., 2., 2., 0., 0.],
       [1., 1., 1., 0., 0.],
       [5., 5., 5., 0., 0.]])

In [85]:
(utility[0][utility[0]!=0]-utility[0][utility[0]!=0].mean())+utility[0][utility[0]!=0].std()

array([2., 2., 0., 0.])

In [86]:
utility[0][utility[0]!=0].std()

1.0

In [97]:
for i in range(7):
    print((utility[i][utility[i]!=0]-.5*utility[i][utility[i]!=0].mean())+2*utility[i][utility[i]!=0].var())

[4.5 4.5 2.5 2.5]
[2.77777778 1.77777778 1.77777778]
[7. 4. 4.]
[0.75 0.75 0.75 1.75]
[1. 1. 1.]
[0.5 0.5 0.5]
[2.5 2.5 2.5]
